In [19]:
import pandas as pd
import numpy as np

In [3]:
lista = [1, 2, 3]

series = pd.Series(lista)

print (series)

0    1
1    2
2    3
dtype: int64


In [4]:
print (series.size)
print (series.index)
print (series.dtype)

3
RangeIndex(start=0, stop=3, step=1)
int64


In [5]:
diccionario = {"python": [5.0, 5.1, 5.2, 5.3], "java": [4.0, 4.1, 4.2, 4.3], "cobol": [3.0, 3.1, 3.2, 3.3]}
diccionario_4 = {"python": 5.0, "java": 4.0, "cobol": 3.0}

series_2 = pd.Series(diccionario)
series_4 = pd.Series(diccionario_4)

print (series_2, "\n")
print (series_4)

python    [5.0, 5.1, 5.2, 5.3]
java      [4.0, 4.1, 4.2, 4.3]
cobol     [3.0, 3.1, 3.2, 3.3]
dtype: object 

python    5.0
java      4.0
cobol     3.0
dtype: float64


In [6]:
print (series_2.size)
print (series_2.index)
print (series_2.dtype)

3
Index(['python', 'java', 'cobol'], dtype='object')
object


In [7]:
print (series_2[0:2], "\n")
print (series_2[["python","cobol"]],"\n")
print (series_2[["python"]],"\n")
print (series_2["python"],"\n")

python    [5.0, 5.1, 5.2, 5.3]
java      [4.0, 4.1, 4.2, 4.3]
dtype: object 

python    [5.0, 5.1, 5.2, 5.3]
cobol     [3.0, 3.1, 3.2, 3.3]
dtype: object 

python    [5.0, 5.1, 5.2, 5.3]
dtype: object 

[5.0, 5.1, 5.2, 5.3] 



In [8]:
series_3 = np.random.randint (low=0, high = 9, size = (3, 3))
print (series_3)

[[7 8 5]
 [2 6 7]
 [3 6 5]]


In [ ]:
print (series_2 * 2)
print (series_2 / 2)
print (series_2 % 2)

In [ ]:
print (series_4[series_4 > 3])

python    5.0
java      4.0
dtype: float64


In [ ]:
serie_listas = [["a", "b", "c"], ["auto", "barco", ""], [1, 2]]
df = pd.Series(serie_listas)
print (df)

0          [a, b, c]
1    [auto, barco, ]
2             [1, 2]
dtype: object


In [13]:
indices_filas = ["nota 1", "nota 2", "nota 3", "nota 4"]
df = pd.DataFrame(diccionario, index = indices_filas)
print (df)


        python  java  cobol
nota 1     5.0   4.0    3.0
nota 2     5.1   4.1    3.1
nota 3     5.2   4.2    3.2
nota 4     5.3   4.3    3.3


In [26]:
df

python  java  cobol
nota 1     5.0   4.0    3.0
nota 2     5.1   4.1    3.1
nota 3     5.2   4.2    3.2
nota 4     5.3   4.3    3.3

In [25]:
# print (df.rename(index = {"nota 1" : "valor 1"}, columns = {"cobol" : "c++"}))
# print (df)
# print (df.reindex(index = ["nota 4", "nota 3", "nota 2", "nota 1"], columns = ["c++", "java", "python", "uno mas"]))
# print (df.iloc[1:3, 0:2])
# print (df.loc[("nota 3", "nota 4"), ("python", "cobol")])
# print (df["python"])
mi_lista = [1, 2, 3, 4]
df["fortran"] = mi_lista
df["validacion"] = df["python"] >= 5.2
print (df)
del df["validacion"]
fortran = df.pop("fortran")
print (fortran)
print (df)
# df = df.append(pd.Series([5.4, 4.4, 3.4], index = ["python", "java", "cobol"]))
print (df.drop(["nota 3", "nota 4"]))
print (df)

        python  java  cobol  fortran  validacion
nota 1     5.0   4.0    3.0        1       False
nota 2     5.1   4.1    3.1        2       False
nota 3     5.2   4.2    3.2        3        True
nota 4     5.3   4.3    3.3        4        True
nota 1    1
nota 2    2
nota 3    3
nota 4    4
Name: fortran, dtype: int64
        python  java  cobol
nota 1     5.0   4.0    3.0
nota 2     5.1   4.1    3.1
nota 3     5.2   4.2    3.2
nota 4     5.3   4.3    3.3
        python  java  cobol
nota 1     5.0   4.0    3.0
nota 2     5.1   4.1    3.1
        python  java  cobol
nota 1     5.0   4.0    3.0
nota 2     5.1   4.1    3.1
nota 3     5.2   4.2    3.2
nota 4     5.3   4.3    3.3


In [75]:
#print (df.info())
print ("")
print (df.shape)
print ("")
print (df.size)
print ("")
print (df.columns)
print ("")
print (df.index)
print ("")
print (df.dtypes)
print ("")
print (df.head(2))
print ("")
print (df.tail(2))



(4, 3)

12

Index(['python', 'java', 'cobol'], dtype='object')

Index(['nota 1', 'nota 2', 'nota 3', 'nota 4'], dtype='object')

python    float64
java      float64
cobol     float64
dtype: object

        python  java  cobol
nota 1     5.0   4.0    3.0
nota 2     5.1   4.1    3.1

        python  java  cobol
nota 3     5.2   4.2    3.2
nota 4     5.3   4.3    3.3
